/* ----- */

#ifndef _EMBEDDED_HAL_BINDINGS
#define _EMBEDDED_HAL_BINDINGS

#ifdef __cplusplus
extern "C" {
#endif

/* Generated with cbindgen:0.1.30 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

typedef enum {
  PIN_PUSH_PULL = 0,
  PIN_OPEN_DRAIN = 1,
} PinConfigs;

typedef enum {
  PIN_INPUT = 0,
  PIN_OUTPUT = 1,
  PIN_ALTERNATE_FCT = 2,
  PIN_ANALOGIC = 3,
} PinModes;

typedef enum {
  MCU_PINS = 0,
  IOE_PINS = 1,
  RADIO_RESET = 2,
} PinNames;

typedef enum {
  PIN_NO_PULL = 0,
  PIN_PULL_UP = 1,
  PIN_PULL_DOWN = 2,
} PinTypes;

typedef size_t *Gpio_t;

typedef void (*irq_ptr)();

typedef struct {
  void *Instance;
} SpiInstance;

typedef struct {
  SpiInstance Spi;
  Gpio_t Nss;
} Spi_s;

typedef Spi_s Spi_t;

typedef struct {
  uint8_t id;
  bool IsRunning;
} TimerEvent_s;

typedef TimerEvent_s TimerEvent_t;

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

void DelayMs(uint32_t ms);

void GpioInit(const Gpio_t *obj,
              PinNames pin,
              PinModes mode,
              PinConfigs config,
              PinTypes pin_type,
              uint32_t val);

void GpioWrite(const Gpio_t *obj, uint8_t val);

uint8_t SX1276GetPaSelect(uint32_t channel);

void SX1276IoIrqInit(irq_ptr irq_handlers[6]);

void SX1276SetAntSw(uint8_t rxTx);

void SX1276SetAntSwLowPower(bool status);

uint16_t SpiInOut(Spi_t *s, uint16_t outData);

void TimerGetCurrentTime();

void TimerGetElapsedTime(const TimerEvent_t *saved_time);

void TimerGetFutureTime(const TimerEvent_t *event_in_future);

void TimerInit(const TimerEvent_t *obj, void (*cb)());

void TimerLowPowerHandler();

void TimerReset(const TimerEvent_t *obj);

void TimerSetValue(const TimerEvent_t *obj, uint32_t value);

void TimerStart(const TimerEvent_t *obj);

void TimerStop(const TimerEvent_t *obj);

void assert_param(bool expr);

void memcpy1(const uint8_t *dst, const uint8_t *src, uint16_t size);

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#ifdef __cplusplus
}
#endif

#endif /* _EMBEDDED_HAL_BINDINGS */

/* ----- */
